"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useEffect, useState } from "react";
import { Activity } from "lucide-react";

export function HealthScore() {
  const [score, setScore] = useState<number | null>(null);
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    fetch("/api/ai/health-score")
      .then((res) => res.json())
      .then((data) => {
        setScore(data.score);
        setSummary(data.summary);
      })
      .catch(() => {
        setScore(65);
        setSummary("Unable to calculate score right now.");
      })
      .finally(() => setLoading(false));
  }, []);

  const getColor = (s: number) => {
    if (s >= 71) return "text-emerald-600";
    if (s >= 41) return "text-amber-500";
    return "text-red-500";
  };

  return (
    <>
      <Card
        className="cursor-pointer transition-shadow hover:shadow-md"
        onClick={() => !loading && score !== null && setOpen(true)}
      >
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium text-muted-foreground flex items-center gap-1.5">
            <Activity className="h-3.5 w-3.5" />
            Financial Health
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="h-16 animate-pulse rounded bg-muted" />
          ) : score !== null ? (
            <>
              <div className="flex items-baseline gap-1">
                <span className={`text-3xl font-bold ${getColor(score)}`}>
                  {score}
                </span>
                <span className="text-sm text-muted-foreground">/100</span>
              </div>
              <p className="mt-1 text-xs text-muted-foreground line-clamp-2">
                {summary}
              </p>
              <p className="mt-1 text-xs text-muted-foreground/60">Tap to read more</p>
            </>
          ) : null}
        </CardContent>
      </Card>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Activity className="h-4 w-4" />
              Financial Health
              {score !== null && (
                <span className={`text-2xl font-bold ${getColor(score)}`}>
                  {score}<span className="text-sm font-normal text-muted-foreground">/100</span>
                </span>
              )}
            </DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground leading-relaxed">{summary}</p>

          <div className="mt-4 rounded-lg bg-muted p-4 space-y-2">
            <p className="text-xs font-medium text-foreground">How is this calculated?</p>
            <p className="text-xs text-muted-foreground">
              Your score is generated by AI using three factors from your current month&apos;s data:
            </p>
            <ul className="text-xs text-muted-foreground space-y-1 list-disc list-inside">
              <li><span className="font-medium text-foreground">Savings rate</span> — how much of your income is left after expenses</li>
              <li><span className="font-medium text-foreground">Budget adherence</span> — what percentage of your budgets are under their limits</li>
              <li><span className="font-medium text-foreground">Spending spread</span> — whether your top spending categories look controlled</li>
            </ul>
            <div className="pt-1 grid grid-cols-4 gap-1 text-xs text-center">
              <div className="rounded bg-emerald-100 dark:bg-emerald-900/30 px-1 py-1">
                <p className="font-medium text-emerald-700 dark:text-emerald-400">80–100</p>
                <p className="text-muted-foreground">Excellent</p>
              </div>
              <div className="rounded bg-blue-100 dark:bg-blue-900/30 px-1 py-1">
                <p className="font-medium text-blue-700 dark:text-blue-400">60–79</p>
                <p className="text-muted-foreground">Good</p>
              </div>
              <div className="rounded bg-amber-100 dark:bg-amber-900/30 px-1 py-1">
                <p className="font-medium text-amber-600 dark:text-amber-400">40–59</p>
                <p className="text-muted-foreground">Fair</p>
              </div>
              <div className="rounded bg-red-100 dark:bg-red-900/30 px-1 py-1">
                <p className="font-medium text-red-600 dark:text-red-400">0–39</p>
                <p className="text-muted-foreground">Needs work</p>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
